#ifndef INC_SENSORDRIVER_CONST_H_
#define INC_SENSORDRIVER_CONST_H_

#define BMI088_ID_TASK								1
#define ATTITUDE_ESTIMATOR_ID_TASK					2
#define RATE_CONTROLLER_ID_TASK						3
#define ATTITUDE_CONTROLLER_ID_TASK					4
#define ATTITUDE_SETPOINT_ID_TASK					5
#define ALTITUDE_ATTITUDE_ID_TASK					6
#define ALTITUDE_CONTROLLER_ID_TASK					7
#endif /* INC_SENSORDRIVER_CONST_H_ */
