#ifndef INC_SENSORDRIVER_CONST_H_
#define INC_SENSORDRIVER_CONST_H_

#define BMI088_ID_TASK								1
#define ATTITUDE_ESTIMATOR_ID_TASK					2
#define RATE_CONTROLLER_ID_TASK						3
#define ATTITUDE_CONTROLLER_ID_TASK					4

#endif /* INC_SENSORDRIVER_CONST_H_ */
